services:
  # PostgreSQL database for Synapse
  postgres:
    image: postgres:15-alpine
    container_name: matrix-postgres
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matrix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse -d synapse"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Synapse caching and workers
  redis:
    image: redis:7-alpine
    container_name: matrix-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - matrix-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Matrix Synapse homeserver
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - synapse_data:/data
    networks:
      - matrix-network
    ports:
      - "8008:8008"  # HTTP port
      - "8448:8448"  # HTTPS federation port
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Synapse Admin interface
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    container_name: matrix-admin
    depends_on:
      - synapse
    environment:
      - REACT_APP_SERVER=http://localhost:8008
    ports:
      - "8080:80"
    networks:
      - matrix-network
    restart: unless-stopped

  # Element Web client (optional)
  element:
    image: vectorim/element-web:latest
    container_name: matrix-element
    volumes:
      - ./docker/element/config.json:/app/config.json:ro
    ports:
      - "8081:80"
    networks:
      - matrix-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  synapse_data:
    driver: local

networks:
  matrix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16