# Legacy Matrix server configuration (for backward compatibility testing)
# This configuration is used when departments are not configured
matrix:
  homeserver: "http://localhost:8008"
  access_token: "syt_c3VwcG9ydA_psMTnoIovNQDWvfXaqMt_0GCzoW"
  admin_access_token: "syt_YWRtaW4_WNlzETRkptENqltWuBNN_10RcpI"
  support_room_id: null
  bot_user_id: "@support:localhost"

# Widget appearance and behavior
widget:
  title: "Support Chat"
  subtitle: "We're here to help!"
  brand_color: "#667eea"
  position: "bottom-right"
  greeting: "Hi! How can we help you today? Please provide your details and we'll connect you with a support agent."
  placeholder_text: "Describe your issue or question..."

# Server configuration
server:
  port: 3003
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://localhost:8000"
    - "file://"
  static_path: "./dist/widget"

# Logging configuration
logging:
  level: "info"
  file: null