# Matrix Chat Support Widget - Production Configuration
# 3 Departments | 9 Users Total | Multi-User Support

departments:
  - id: "support"
    name: "General Support"
    description: "Technical help and general inquiries"
    icon: "🎧"
    color: "#667eea"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_c3VwcG9ydF9hZ2VudDE_GOvIRBMUxypSdAwpcIKj_0uUQL9"
      admin_access_token: "syt_YWRtaW4_VTRbtfkvKOWHKnZvNboG_4e5zAu"
      support_room_id: null
      bot_user_id: "@support_agent1:localhost"
      department_users:
        - "@support_agent1:localhost"
        - "@support_agent2:localhost"
        - "@support_agent3:localhost"
        - "@observer:localhost"
      spaceConfig:
        channelId: "web-chat"
        autoCreateDepartmentSpace: true
        departmentSpaceNaming: "Web-Chat - General Support"
    widget:
      greeting: "Hi! How can our support team help you today?"
      placeholder_text: "Describe your technical issue or question..."

  - id: "commerce"
    name: "Commerce Support"
    description: "Sales, billing, and order support"
    icon: "💼"
    color: "#10b981"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_Y29tbWVyY2VfYWdlbnQx_hlJesSVuBwCVDdUGZrNf_2tAq7c"
      admin_access_token: "syt_YWRtaW4_VTRbtfkvKOWHKnZvNboG_4e5zAu"
      support_room_id: null
      bot_user_id: "@commerce_agent1:localhost"
      department_users:
        - "@commerce_agent1:localhost"
        - "@commerce_agent2:localhost"
        - "@commerce_agent3:localhost"
        - "@commerce_agent4:localhost"
        - "@observer:localhost"
      spaceConfig:
        channelId: "web-chat"
        autoCreateDepartmentSpace: true
        departmentSpaceNaming: "Web-Chat - Commerce Support"
    widget:
      greeting: "Hello! How can we help with your purchase or order?"
      placeholder_text: "Tell us about your order or purchase inquiry..."

  - id: "identification"
    name: "Account Verification"
    description: "Identity verification and account issues"
    icon: "🔒"
    color: "#f59e0b"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_aWRlbnRpZnlfYWdlbnQx_BKcJaMAeAkdtJRYqqifv_0UtYlY"
      admin_access_token: "syt_YWRtaW4_VTRbtfkvKOWHKnZvNboG_4e5zAu"
      support_room_id: null
      bot_user_id: "@identify_agent1:localhost"
      department_users:
        - "@identify_agent1:localhost"
        - "@identify_agent2:localhost"
        - "@observer:localhost"
      spaceConfig:
        channelId: "web-chat"
        autoCreateDepartmentSpace: true
        departmentSpaceNaming: "Web-Chat - Account Verification"
    widget:
      greeting: "We'll help you verify your account securely."
      placeholder_text: "Please describe the account issue you're experiencing..."

# Legacy Matrix configuration (fallback)
matrix:
  homeserver: "http://localhost:8008"
  access_token: "syt_YWRtaW4_VTRbtfkvKOWHKnZvNboG_4e5zAu"
  admin_access_token: "syt_YWRtaW4_VTRbtfkvKOWHKnZvNboG_4e5zAu"
  support_room_id: null
  bot_user_id: "@admin:localhost"

# Widget appearance
widget:
  title: "Customer Support"
  subtitle: "We're here to help!"
  brand_color: "#667eea"
  position: "bottom-right"
  department_selection:
    title: "How can we help you today?"
    subtitle: "Choose the team that best matches your needs"
    show_descriptions: true
    layout: "grid"

# Social Media Integration
social_media:
  - id: "telegram_support"
    name: "Telegram Bot"
    platform: "telegram"
    icon: "✈️"
    color: "#0088cc"
    enabled: true
    config:
      bot_username: "QWMatrixTestBot"
      bot_token: "8497512931:AAGddNooUhvamOws_7ohRTQRgAulQPs9jGM"
      welcome_message: "Welcome! Please select the department you need help with."
      auto_reply: true
      departments:
        - department_id: "support"
          command: "/start_support"
          channel_specific: true
        - department_id: "commerce"
          command: "/start_commerce"
          channel_specific: true
        - department_id: "identification"
          command: "/start_id"
          channel_specific: true

# Communication Channels
communication_channels:
  - type: "web"
    id: "web_chat"
    name: "Web Chat"
    description: "Chat directly with our support team"
    icon: "💬"
    color: "#667eea"
    available: true
  - type: "social"
    id: "telegram_channel"
    name: "Telegram"
    description: "Continue the conversation on Telegram"
    icon: "✈️"
    color: "#0088cc"
    available: true
    social_media_id: "telegram_support"

# Server configuration
server:
  port: 3001
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://localhost:8000"
    - "file://"
  static_path: "./dist/widget"

# Observer user (read-only access to all departments)
observer:
  enabled: true
  user_id: "@observer:localhost"
  password: "observer123"  # Change this after creation
  access_token: "syt_b2JzZXJ2ZXI_zkpZTxvMHkqQLaPZqzan_0AOoN0"
  display_name: "Support Observer"
  auto_invite: true
  permissions: "read_only"
  description: "Manager with read-only access to all conversations"

# Logging
logging:
  level: "info"
  file: null
