# Telegram Department Router Configuration

# Telegram Bot Configuration
telegram:
  api_id: 22451908
  api_hash: "40f6de1fd19af98c0b60c364a30d5fa9"
  bot_token: "8497512931:AAGddNooUhvamOws_7ohRTQRgAulQPs9jGM"

# Department Configuration (matching the main config)
departments:
  - id: "support"
    name: "General Support"
    description: "Technical help and general inquiries"
    icon: "🎧"
    color: "#667eea"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_c3VwcG9ydA_TAhFIypfvsXmZlLYkoAs_3vBX8q"
      bot_user_id: "@support:localhost"
      support_users: ["@support:localhost", "@admin:localhost"]

  - id: "tech_support"
    name: "Tech Support"
    description: "Advanced technical assistance"
    icon: "💼"
    color: "#10b981"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_c3VwcG9ydA_TAhFIypfvsXmZlLYkoAs_3vBX8q"
      bot_user_id: "@support:localhost"
      support_users: ["@tech_support:localhost", "@admin:localhost"]

  - id: "identification"
    name: "Account Verification"
    description: "Identity verification and account issues"
    icon: "🔒"
    color: "#f59e0b"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_c3VwcG9ydA_TAhFIypfvsXmZlLYkoAs_3vBX8q"
      bot_user_id: "@support:localhost"
      support_users: ["@identification:localhost", "@admin:localhost"]

  - id: "commerce"
    name: "Sales & Commerce"
    description: "Purchase questions and order support"
    icon: "💰"
    color: "#8b5cf6"
    matrix:
      homeserver: "http://localhost:8008"
      access_token: "syt_c3VwcG9ydA_TAhFIypfvsXmZlLYkoAs_3vBX8q"
      bot_user_id: "@support:localhost"
      support_users: ["@commerce:localhost", "@admin:localhost"]

# Bot Behavior Configuration
bot_settings:
  session_timeout: 3600  # 1 hour in seconds
  max_concurrent_sessions: 1000
  welcome_message: "👋 Welcome! Please select the department you'd like to contact:"
  department_selection_timeout: 300  # 5 minutes
  auto_create_rooms: true
  room_name_template: "Telegram Support - {department} - {user}"
  room_topic_template: "Support conversation from Telegram user {username}"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/tmp/telegram-router.log"