# Matrix Spaces Configuration
# This file defines the organizational hierarchy for Matrix rooms
# Supports multi-channel communication (Web-Chat, Telegram, Facebook, etc.)

# Root space configuration
spaces:
  rootSpace:
    name: "Customer Support"
    description: "Central hub for all customer support communications"
    avatar: "🏢"
    topic: "Organized customer support across all communication channels"
    visibility: "private"  # private, public, invite_only
    powerLevels:
      invite: 50
      kick: 50
      ban: 75
      redact: 50
      events_default: 0
      users_default: 0
      state_default: 50
    
  # Communication channel spaces (each channel gets its own organizational space)
  communicationChannels:
    - id: web-chat
      name: "Web-Chat"
      description: "All conversations from the website chat widget"
      avatar: "💻"
      topic: "Customer conversations from web widget"
      parentSpaceId: null  # Will be set to rootSpace ID after creation
      visibility: "private"
      enabled: true
      
    - id: telegram
      name: "Telegram"
      description: "All conversations from Telegram bot"
      avatar: "✈️"
      topic: "Customer conversations from Telegram integration"
      parentSpaceId: null  # Will be set to rootSpace ID after creation
      visibility: "private"
      enabled: false  # Future implementation
      
    - id: facebook
      name: "Facebook"
      description: "All conversations from Facebook Messenger"
      avatar: "📘"
      topic: "Customer conversations from Facebook Messenger bridge"
      parentSpaceId: null  # Will be set to rootSpace ID after creation
      visibility: "private"
      enabled: false  # Future implementation

# Space management settings
settings:
  # Automatic space setup on server startup
  autoSetupSpaces: true
  
  # Space creation mode: auto (create if missing), manual (require manual setup), disabled (no spaces)
  spaceCreationMode: "auto"
  
  # Repair space hierarchy on startup (fix broken parent-child relationships)
  repairHierarchyOnStart: true
  
  # Naming pattern for department sub-spaces: {channelName} - {departmentName}
  spaceNamingPattern: "{channelName} - {departmentName}"
  
  # Space room limit (prevent runaway space creation)
  maxRoomsPerSpace: 1000
  
  # Space hierarchy depth limit
  maxHierarchyDepth: 5
  
  # Automatic space cleanup (remove empty spaces after N days)
  autoCleanup:
    enabled: false
    emptySpaceRetentionDays: 30

# Department space configuration
# Each department gets a sub-space within each communication channel
departmentSpaces:
  # Configuration for web-chat department spaces
  web-chat:
    # Auto-create department spaces within the web-chat space
    autoCreateDepartmentSpaces: true
    
    # Department space visibility
    visibility: "private"
    
    # Naming pattern for department rooms within spaces
    roomNamingPattern: "{userName} - {departmentName} #{conversationId}"
    
    # Room organization settings
    organization:
      # Group rooms by: none, date, department, user
      groupBy: "department"
      
      # Maximum rooms per department space
      maxRoomsPerDepartment: 500
      
      # Auto-archive old rooms after N days
      autoArchiveAfterDays: 90
      
  # Future: telegram department configuration
  telegram:
    autoCreateDepartmentSpaces: false
    visibility: "private"
    roomNamingPattern: "{userName} (Telegram) - {departmentName} #{conversationId}"
    
  # Future: facebook department configuration  
  facebook:
    autoCreateDepartmentSpaces: false
    visibility: "private"
    roomNamingPattern: "{userName} (Facebook) - {departmentName} #{conversationId}"

# Space appearance and UI settings
appearance:
  # Show space hierarchy in chat header
  showSpaceInHeader: true
  
  # Display communication channel origin in room names
  displayChannelOrigin: true
  
  # Allow users to switch between spaces (future feature)
  allowSpaceSwitching: false
  
  # Space icons and styling
  spaceIcons:
    rootSpace: "🏢"
    webChat: "💻"
    telegram: "✈️"
    facebook: "📘"
    
  # Space colors (used for UI elements)
  spaceColors:
    rootSpace: "#4F46E5"
    webChat: "#667eea"
    telegram: "#0088cc"
    facebook: "#1877f2"

# Logging and monitoring
logging:
  # Log space operations
  logSpaceOperations: true
  
  # Log space hierarchy changes
  logHierarchyChanges: true
  
  # Log room additions/removals from spaces
  logRoomSpaceChanges: true
  
  # Space operation log level: debug, info, warn, error
  spaceLogLevel: "info"

# Backup and recovery
backup:
  # Backup space configuration on changes
  backupOnChanges: true
  
  # Backup directory for space configurations
  backupDirectory: "./config/backups/spaces"
  
  # Maximum number of backup files to keep
  maxBackupFiles: 10
  
  # Export space hierarchy to file
  exportHierarchy: true
  exportPath: "./config/space-hierarchy.json"

# Matrix API specific settings
matrix:
  # API rate limiting for space operations
  rateLimiting:
    spaceCreation: 5    # max 5 space creations per minute
    roomToSpace: 30     # max 30 room-to-space operations per minute
    hierarchyQuery: 60  # max 60 hierarchy queries per minute
  
  # Retry configuration for failed operations
  retryPolicy:
    maxRetries: 3
    retryDelayMs: 1000
    exponentialBackoff: true
  
  # Space synchronization settings
  sync:
    # Re-sync space hierarchy every N minutes
    syncIntervalMinutes: 60
    
    # Validate space integrity on sync
    validateIntegrity: true
    
    # Auto-repair detected issues
    autoRepair: true

# Feature flags for development and testing
features:
  # Enable space debugging mode
  debugMode: false
  
  # Enable space analytics collection
  analytics: false
  
  # Enable experimental space features
  experimentalFeatures: false
  
  # Enable space performance monitoring
  performanceMonitoring: true

# Migration settings for existing deployments
migration:
  # Migrate existing rooms to spaces on startup
  migrateExistingRooms: true
  
  # Migration strategy: immediate, gradual, manual
  migrationStrategy: "gradual"
  
  # Backup existing configuration before migration
  backupBeforeMigration: true
  
  # Preserve existing room structure during migration
  preserveRoomStructure: true
  
  # Migration log file
  migrationLogFile: "./logs/space-migration.log"